services:
    db:
        image: postgres:16.3
        container_name: postgres-db
        environment:
            POSTGRES_DB: gopher-social-network
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin123
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    redis:
        image: redis:7.2-alpine
        restart: unless-stopped
        container_name: redis
        ports:
            - "6379:6379"
        command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD} 

volumes:
    db-data:
